language: python

python:
  - "3.7"

services:
  - mysql

env:
  - DJANGO=2.2.3 
  - DB=mysql
  - CODECOV_TOKEN="c7fd2be3-f209-4e67-aff2-0d5531ff6019"
install:
  - pip install -r requirements.txt

before_sqript:
  - mysql -e 'create database test;' -u root

script:
  - cd app/
  - coverage run --source='.' --omit=*/migrations/* manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)